abbr = {
"afaik": "as far as i know",
"abt": "about",
"af": "as fuck",
"afk": "away from keyboard",
"aii": "alright",
"aight": "alright",
"aka": "also known as",
"ama": "ask me anything",
"aoe": "area of effect",
"arent": "aren't",
"bf": "boyfriend",
"bg": "background",
"bae": "baby",
"bb": "baby",
"bbq": "barbeque",
"bc": "because",
"bcos": "because",
"bday": "birthday",
"bff": "best friend",
"bih": "bitch",
"btw": "by the way",
"byob": "bring your own booze",
"cant": "can't",
"'cause": "because",
"couldnt": "couldn't",
"couldve": "could've",
"cld": "could",
"cos": "because",
"cra": "crazy",
"cray": "crazy",
"cuz": "beacuse",
"dafuq": "the fuck",
"dc'd": "disconnected",
"dcd": "disconnected",
"dgaf": "don't give a fuck",
"didnt": "didn't",
"doesnt": "doesn't",
"dont": "don't",
"dis": "this",
"diy": "do-it-yourself",
"dl": "down low",
"dm": "direct message",
"doe": "though",
"dunno": "don't know",
"dw": "don't worry",
"eli5": "explain like i'm five",
"enuf": "enough",
"eta": "estimated time of arrival",
"ez": "easy",
"fb": "facebook",
"ffa": "free for all",
"foh": "fuck out of here",
"ftw": "for the win",
"fu": "fuck you",
"fubar": "fucked up beyond all recognition",
"fwb": "friends with benefits",
"fym": "what the fuck do you mean",
"gdi": "god damn it",
"gf": "girlfriend",
"gj": "good job",
"gl": "good luck",
"glhf": "good luck, have fun",
"gn": "goodnight",
"gna": "going to",
"gnight": "goodnight",
"gnite": "goodnight",
"gonna": "going to",
"goin": "going",
"gr8": "great",
"gtfo": "get the fuck out",
"gtfoh": "get the fuck out of here",
"gtg": "got to go",
"gud": "good",
"h8": "hate",
"hadnt": "hadn't",
"hasnt": "hasn't",
"havent": "haven't",
"hed": "he'd",
"hes": "he's",
"howd": "how'd",
"howll": "how'll",
"hows": "how's",
"halp": "help",
"hawt": "hot",
"hbd": "happy birthday",
"h-bday": "happy birthday",
"hbu": "how about you",
"id": "i'd",
"ill": "i'll",
"im": "i'm",
"ive": "i've",
"isnt": "isn't",
"itll": "it'll",
"idc": "i don't care",
"idgaf": "i don't give a fuck",
"idk": "i don't know",
"idts": "i don't think so",
"idunno": "i don't know",
"ig": "instagram",
"ight": "alright",
"ii": "alright",
"iirc": "if i remember correctly",
"ik": "i know",
"ikr": "i know, right",
"ilu": "i love you",
"ily": "i love you",
"ilysm": "i love you so much",
"imo": "in my opinion",
"inv": "invite",
"irl": "in real life",
"jelly": "jealous",
"jk": "just kidding",
"jw": "just wondering",
"k": "okay",
"kk": "okay",
"kewl": "cool",
"kms": "kill myself",
"kys": "kill yourself",
"l33t": "elite",
"l8r": "later",
"lets": "let's",
"lfg": "looking for group",
"lfm": "looking for more",
"lf1m": "looking for one more",
"lf2m": "looking for two more",
"lf3m": "looking for three more",
"lf4m": "looking for four more",
"lf5m": "looking for five more",
"lmk": "let me know",
"ly": "love you",
"lysm": "love you so much",
"mightve": "might've",
"mustve": "must've",
"m8": "mate",
"meh": "whatever",
"mfw": "my face when",
"mkay": "okay",
"mrw": "my reaction when",
"msg": "message",
"n00b": "newbie",
"noob": "newbie",
"nbd": "no big deal",
"ngl": "not going to lie",
"nm": "nothing much",
"np": "no problem",
"nsfw": "not safe for work",
"nsfl": "not safe for life",
"nvm": "never mind",
"nvr": "never",
"obv": "obviously",
"obvi": "obviously",
"ofc": "of course",
"og": "original",
"omfg": "oh my fucking god",
"omg": "oh my god",
"omw": "oh my way",
"ootd": "one of those days",
"p": "pretty",
"pce": "peace",
"pls": "please",
"plz": "please",
"pm": "private message",
"pov": "point of view",
"ppl": "people",
"prob": "probably",
"probs": "probably",
"prolly": "porbably",
"pvp": "player versus player",
"qt": "cutie",
"r": "are",
"rly": "really",
"rt": "retweet",
"shes": "she's",
"shouldve": "should've",
"shouldnt": "shouldn't",
"smh": "shaking my head",
"srs": "serious",
"srsly": "seriously",
"sry": "sorry",
"stfu": "shut the fuck up",
"str8": "straight",
"sumn": "something",
"sum'n": "something",
"sup": "what's up",
"thatd": "that'd",
"thats": "that's",
"thered": "there'd",
"theres": "there's",
"theyd": "they'd",
"theyll": "they'll",
"theyre": "they're",
"theyve": "they've",
"tbd": "to be determined",
"tbh": "to be honest",
"tbt": "throwback thursday",
"thx": "thanks",
"thnx": "thanks",
'tldr': "too long, didn't read",
"tl;dr": "too long, didn't read",
"tmi": "too much information",
"turnt": "turned up",
"ttyl": "talk to you later",
"ty": "thank you",
"u": "you",
"urs": "yours",
"v": "very",
"vc": "voice chat",
"w/": "with",
"wasnt": "wasn't",
"werent": "weren't",
"whatll": "what'll",
"whatre": "what're",
"whats": "what's",
"whatve": "what've",
"whens": "when's",
"whered": "where'd",
"wheres": "where's",
"wholl": "who'll",
"whos": "who's",
"whove": "who've",
"wont": "won't",
"wouldve": "would've",
"wouldnt": "wouldn't",
"wat": "what",
"wbu": "what about you",
"w/e": "whatever",
"whatevs": "whatever",
"wrt": "with regard to",
"w/o": "without",
"wtf": "what the fuck",
"wth": "what the hell",
"wya": "where are you",
"wyd": "what are you doing",
"y": "why",
"yall": "y'all",
"yalld": "y'all'd",
"yalldve": "y'all'd've",
"yallre": "y'all're",
"yallve": "y'all've",
"youd": "you'd",
"youdve": "you'd've",
"youll": "you'll",
"youre": "you're",
"youve": "you've"
}
